spring:
  application:
    name: techprocess-dev-system-server

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      show-sql: true

jwt:
  secret-key: ${JWT_SECRET}
  access-expired-time: 3600000
  refresh-expired-time: 86400000